global
       daemon
       maxconn 1024

defaults
       mode http
       timeout connect 5000ms
       timeout client 50000ms
       timeout server 50000ms

frontend http-in
       bind *:8080
       default_backend servers

backend servers
       server server1 nodejs01:8080 maxconn 512
       server server2 nodejs02:8080 maxconn 512
